//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Parking_cad.rc 使用
//
#define IDS_PROJNAME                    100
#define IDC_RADIO_Default               100
#define IDC_RAD_A0                      100
#define IDC_RADIO_OtherLength           101
#define IDC_RAD_A1                      101
#define IDD_ARX_MODAL                   102
#define IDC_EDIT_Length                 102
#define IDC_RAD_A2                      102
#define IDC_EDIT_WIDTH                  103
#define IDC_RAD_A3                      103
#define IDC_EDIT_LaneWidth              104
#define IDC_RAD_A4                      104
#define IDC_EDIT_SquarecolumnLength     105
#define IDD_DLG_WAITTING_SHOW_RES       105
#define IDC_EDIT_FRAME_LENGTH           105
#define IDC_EDIT_SquareColumnWidth      106
#define IDC_EDIT_FRAME_WIDTH            106
#define IDC_BUTTON_GetStartPoint        107
#define IDD_DLG_ADD_FRAME               107
#define IDC_BUTTON_GetRetreatline       108
#define IDD_DLG_ADD_EQUIPMENT_ROOM      108
#define IDD_DIALOG_CONFIG               114
#define IDD_DLG_BIP_LOGIN               116
#define IDD_DIALOG_SLIDER               118
#define IDC_CHECK_Partition             119
#define IDD_DLG_FINDCLOUD               120
#define IDD_DLG_VENTILATE               122
#define IDD_DLG_VILLAGE                 124
#define IDD_DLG_LIFEPUMPHOUSE           126
#define IDC_COMBO_Direction             128
#define IDD_DLG_LIVEWATERTANK           128
#define IDC_COMBO_OutlineLayer          129
#define IDC_COMBO_ShearwallLayer        130
#define IDD_DLG_FIREPUMPHOUSE           130
#define IDC_EDIT_StartPoint             131
#define IDC_EDIT_RetreatLine            132
#define IDD_DLG_FIREPOOL                132
#define IDC_EDIT_PARTITION_LINE         133
#define IDC_STATIC_m                    134
#define IDC_STC_GIF                     135
#define IDC_EDIT_PARKINGCOUNT           136
#define IDD_DLG_ENTRANCESET             136
#define IDC_EDIT_NON_CONVEXLEVEL        137
#define IDC_STA_STATUS                  138
#define IDC_STA_PREVIEW                 138
#define IDD_DLG_AXISNUMZOOM             138
#define IDC_BUTTON_VENTILATE            139
#define IDC_BUTTON_VILLAGE_SET          140
#define IDI_ICON_DOWN                   140
#define IDC_BUTTON_LIFEPUMPHOUSE_SET    141
#define IDC_BUTTON_LIVINGWATERTANK_SET  142
#define IDI_ICON_UP                     142
#define IDC_BUTTON_FIREPUMPHOUSE_SET    143
#define IDC_BUTTON_FIREPOOL_SET         144
#define IDI_ICON_ZOOM                   144
#define IDC_BUTTON_CUSTOM               145
#define IDD_DLG_TOOLBAR                 147
#define IDD_DIALOG_RESETENTITYLAYER     149
#define IDI_ICON_AIPARK                 152
#define IDC_BUTTON_GETENDPOINT          161
#define IDC_EDIT_SHOWENDPOINT           163
#define IDC_EDIT_USER                   163
#define IDC_EDIT_SHOWVALUE              163
#define IDC_BUTTON_EXCHANGE             164
#define IDC_BUTTON_MANYSHOW             164
#define IDC_EDIT_PASSWORD               178
#define IDC_CHK_SAVE_PWD                180
#define IDC_CHECK_MANYSHOW              181
#define IDC_BUTTON_PARTPLAN             182
#define IDC_LIST                        183
#define IDC_LAYERLIST                   184
#define IDC_ANIMATE1                    184
#define IDC_BUTTON_CHECK                185
#define IDC_EDIT_LIST                   186
#define IDC_EDIT1                       186
#define IDC_EDIT2                       187
#define IDC_COMBO_CONFIGCHOOSE          188
#define IDC_VILLAGE_CHECK               188
#define IDC_COMBO_LINEWIDTH             189
#define IDC_EDIT_TOTALAREA              189
#define IDC_COMBO_LINETYPE              190
#define IDC_EDIT_VILL_PROPORTION        190
#define IDC_EDIT_LPH_PRO                191
#define IDC_EDIT_HOUSEHOLDS             192
#define IDC_EDIT_LPH_PRO2               192
#define IDC_EDIT_LWTPRO                 193
#define IDC_FIREPUMP_CHECK              194
#define IDC_FIREPUMP_CHECK2             195
#define IDC_SLIDER_CONTROL              196
#define IDC_EDIT_STOREYHEIGHT           196
#define IDC_EDIT_FP_PROPORTION          197
#define IDC_FP_CONSIDERCHECK            198
#define IDC_FP_SUPPLYCHECK              199
#define IDC_BUTTON_GETENTRANCEPL        200
#define IDC_EDIT_ENTRANCE_WIDTH         201
#define IDC_EDIT_ENTRANCEDATA           202
#define IDC_EDIT_BASEMENT_HEIGHT        203
#define IDC_BUTTON_AXISNUM_UP           205
#define IDC_BUTTON_AXISNUM_DOWN         207
#define IDC_EDIT_STEPVALUE              208
#define IDC_SHOW_SCALEVALUE             210
#define IDC_BTN_SELOUTLINELAYER         213
#define IDC_BTN_SHEARWALLLAYER          214
#define IDC_TREE_NAV                    215
#define IDC_STATIC1                     216
#define IDC_STATIC2                     217
#define IDC_STATIC3                     218
#define IDC_CHK_SHOW_CLOUDLINE_LAYER    218
#define IDC_LIST1                       219
#define IDC_COMBOX_CREATEID             220
#define IDC_BUTTON1                     221
#define IDC_BUTTON_TRUE                 221
#define IDC_STA_BK                      222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         223
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
